language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script:
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rake spec
before_script:
  - bundle exec rake db:create RAILS_ENV=test
bundler_args: --binstubs=./bundler_stubs
